#---------------------------->> Configurations <<----------------------------#
#       Set up the Bot with some settings. They only apply to Modules!       #
#  Stick to the given value types. Changing types or entering false values   #
#                        lead to errors or shutdowns                         #
#----------------------------------------------------------------------------#

Suggestion-Channel:
  - 908621996009619477: "922851208295755808"