#--------------------------->> Game Settings <<---------------------------#
#                   Replace these values with your tokens                 #
#           !IMPORTANT! - Do not share these values with anyone!          #
#-------------------------------------------------------------------------#

TicTacToe-Channel: 988144444874326026
FourInARow-Channel: 988427204075618334