#--------------------------->> Game Settings <<---------------------------#
#                   Replace these values with your tokens                 #
#           !IMPORTANT! - Do not share these values with anyone!          #
#-------------------------------------------------------------------------#

TicTacToe-Channel: 988144444874326026
FourInARow-Channel: 988427204075618334

FourInARow-Emotes:
  - ":blue_circle:"
  - ":brown_circle:"
  - ":green_circle:"
  - ":orange_circle:"
  - ":purple_circle:"
  - "<:OMEGALUL:816312423115915305>"
  - "<:D_:852962423094509638>"
  - "<:xD:949671949670428733>"
  - ":rage:"
  - ":flushed:"
  - ":nerd:"
  - ":sunglasses:"