#--------------------------->> Game Settings <<---------------------------#
#                   Replace these values with your tokens                 #
#           !IMPORTANT! - Do not share these values with anyone!          #
#-------------------------------------------------------------------------#

Connect4-RawEmotes:
  - 🔵: 100
  - 🟤: 100
  - 🟢: 100
  - 🟠: 100
  - 🟣: 100
  - 😡: 300
  - 😳: 300
  - 🤓: 300
  - 😎: 300

Connect4-SpecialEmotes:
  - "<:OMEGALUL:816312423115915305>"
  - "<:D_:852962423094509638>"
  - "<:xD:949671949670428733>"
  - "<:Pumpkin:895271226304503858>"
  - "<:protect:885240719202197545>"
  - "<:mcHeart:748568708900847658>"